### ISSUE TITLE
LAB 1

### ISSUE THREAD

**Issue by dinohromic** [Mouqla/TDA553-lab1#3]
COMMENT: Things that are marked as CRITICAL are things you need to change in order to pass the assignment. 

TASK 1:

CRITICAL: You have to separate the duplicated code that is in Volvo and Saab. There is still a lot of code that could be put in the Car class instead. This must be done in order to pass the assignment. There is no constructor in the Car class. This also needs to be implemented in order for the subclasses to inherit the code that they have in common. 

TASK 2:
There are no tests for movement in your program, see my comments on TASK 3 underneath. 

TASK 3:
There are no tests regarding movement. Also the tests should NOT be in the same class as the object you would like to test. You need to create a test file that seperates the tests from the actual objects that need to be tested. In this test file you will have to create test classes that test the implementation of an object. Also, tests for setters that you have written are unnecessary such as testDoors and testSetColor , etc. 

Comments:
I will refer this to Robin so that you can have a talk about how he can help you progress in the course and actually complete the assignments.

**Comment by dinohromic** [comment]
Everything that I have commented on are CRITICAL issues and they need to be changed in order for you to pass the assignment.

**Comment by radams78** [comment]
Thank you for referring this to me @dinohromic.

There are some things that @dinohromic misunderstood. I see that you do have tests for movement, and it is good to test setters - ideally every line of code should be tested.

These are the things that must be corrected before you have passed lab 1:

1. Encapsulation: Make all instance variables private. (This will require some changes to the code, including writing a constructor for the Car class).
2. Sanity check: It is possible for an object of type Saab95 to get a speed that is > enginePower if we call gas(1) when its speed is 125, or to get a speed that is < 0 if we call brake(1) when its speed is 0
3. OCP: There is duplicated code in the gas(), brake(), incrementSpeed and decrementSpeed() methods in Volvo240 and Saab95 classes. Put all duplicated code either in Car, or in a class that both Volvo240 and Saab95 delegate to. (Hint: This will be easier to do if you fix the bug under number 2 first. The simplest solution is to put the common code in Car.)
4. Place tests in a separate class from the class that they are testing.
5. In lab1reflection.txt, make reference to the Open-Closed Principle in your answer to the first question. In your answer to the second question you only mention the first sanity check ("gas() and brake() only accept values in the interval [0,1],") - explain how you implemented the other three.

Good luck!
